version: '3.8'

services:
  # Frontend Service (React)
  frontend:
    build:
      context: . # Path to your frontend code
      dockerfile: Dockerfile.frontend  # Path to the Dockerfile in the components folder
    ports:
      - "8080:80"  # Expose the React app on port 8080

  # Backend Service (Flask API)
  backend:
    build:
      context: .  # Root context for Flask API
      dockerfile: Dockerfile.api  # Path to the backend Dockerfile in the root directory
    ports:
      - "5000:5000"  # Expose the Flask API on port 5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/microshop-orders  # MongoDB connection string
    depends_on:
      - mongo  # Ensure MongoDB starts before the backend

  # MongoDB Service
  mongo:
    image: mongo:latest  # Use the latest MongoDB image
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017

volumes:
  mongo_data:  # Persistent volume for MongoDB data